server:
  port: 80

spring:
  application:
    name: abc
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: 121
    prefer-ip-address: true
    
info: 
  app.name: adfadf